package dev.ch8n.common.utils

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.colorspace.ColorSpaces


fun String.toColor(): Color {
    val (r, g, b, a) = this.split("|")
    return Color(
        red = r.toFloat(),
        green = g.toFloat(),
        blue = b.toFloat(),
        alpha = a.toFloat(),
        colorSpace = ColorSpaces.Srgb
    )
}


fun Color.toDbString(): String {
    toString()
    return "$red|$green|$blue|$alpha"
}


object ColorsUtils {

    val colors by lazy { getCoolColors() }

    val randomColor: Color
        get() {
            val randomColorGroup = colors.shuffled().first()
            val (_, color) = randomColorGroup.shuffled().first()
            return color
        }

    private fun getCoolColors(): List<List<Pair<String, Color>>> {
        val finalList = mutableListOf<List<Pair<String, Color>>>()

        val listFirst = mutableListOf<Pair<String, Color>>()
        listFirst.add(Pair("GAINSBORO", CoolColor.GAINSBORO))
        listFirst.add(Pair("LIGHT GREY", CoolColor.LIGHT_GREY))
        listFirst.add(Pair("SILVER", CoolColor.SILVER))
        listFirst.add(Pair("LAWN GREEN", CoolColor.LAWN_GREEN))
        listFirst.add(Pair("LIME", CoolColor.LIME))
        listFirst.add(Pair("LIME GREEN", CoolColor.LIME_GREEN))
        finalList.add(listFirst)

        val listSecond = mutableListOf<Pair<String, Color>>()
        listSecond.add(Pair("DARK GREY", CoolColor.DARK_GREY))
        listSecond.add(Pair("GREY", CoolColor.GREY))
        listSecond.add(Pair("DIM GREY", CoolColor.DIM_GREY))
        listSecond.add(Pair("DARK OLIVE", CoolColor.DARK_OLIVE))
        listSecond.add(Pair("MEDIUM AQUAMARINE", CoolColor.MEDIUM_AQUAMARINE))
        listSecond.add(Pair("DARK SEAGREEEN", CoolColor.DARK_SEAGREEN))
        finalList.add(listSecond)

        val listThird = mutableListOf<Pair<String, Color>>()
        listThird.add(Pair("LIGHT SLATE GREY", CoolColor.LIGHT_SLATE_GREY))
        listThird.add(Pair("SLATE GREY", CoolColor.SLATE_GREY))
        listThird.add(Pair("DARK SLATE GREY", CoolColor.DARK_SLATE_GREY))
        listThird.add(Pair("LIGHT SEAGREEN", CoolColor.LIGHT_SEAGREEN))
        listThird.add(Pair("DARK CYAN", CoolColor.DARK_CYAN))
        listThird.add(Pair("TEAL", CoolColor.TEAL))
        finalList.add(listThird)

        val listFourth = mutableListOf<Pair<String, Color>>()
        listFourth.add(Pair("BLACK", CoolColor.BLACK))
        listFourth.add(Pair("CORN SILK", CoolColor.CORN_SILK))
        listFourth.add(Pair("BLANCHED ALMOND", CoolColor.BLANCHED_ALMOND))
        listFourth.add(Pair("LAVENDER", CoolColor.LAVENDER))
        listFourth.add(Pair("THISTLE", CoolColor.THISTLE))
        listFourth.add(Pair("PLUM", CoolColor.PLUM))
        finalList.add(listFourth)

        val listFifth = mutableListOf<Pair<String, Color>>()
        listFifth.add(Pair("BISQUE", CoolColor.BISQUE))
        listFifth.add(Pair("NAVAJO WHITE", CoolColor.NAVAJO_WHITE))
        listFifth.add(Pair("WHEAT", CoolColor.WHEAT))
        listFifth.add(Pair("VIOLET", CoolColor.VIOLET))
        listFifth.add(Pair("ORCHID", CoolColor.ORCHID))
        listFifth.add(Pair("FUCHSIA", CoolColor.FUCHSIA))
        finalList.add(listFifth)

        val listSixth = mutableListOf<Pair<String, Color>>()
        listSixth.add(Pair("BURLYWOOD", CoolColor.BURLYWOOD))
        listSixth.add(Pair("TAN", CoolColor.TAN))
        listSixth.add(Pair("ROSY BROWN", CoolColor.ROSY_BROWN))
        listSixth.add(Pair("MAGENTA", CoolColor.MAGENTA))
        listSixth.add(Pair("MEDIUM ORCHID", CoolColor.MEDIUM_ORCHID))
        listSixth.add(Pair("MEDIUM PURPLE", CoolColor.MEDIUM_PURPLE))
        finalList.add(listSixth)

        val listSeventh = mutableListOf<Pair<String, Color>>()
        listSeventh.add(Pair("SANDY BROWN", CoolColor.SANDY_BROWN))
        listSeventh.add(Pair("GOLDEN ROD", CoolColor.GOLDEN_ROD))
        listSeventh.add(Pair("DARK GOLDEN ROD", CoolColor.DARK_GOLDEN_ROD))
        listSeventh.add(Pair("REBECCA PURPLE", CoolColor.REBECCA_PURPLE))
        listSeventh.add(Pair("BLUE VIOLET", CoolColor.BLUE_VIOLET))
        listSeventh.add(Pair("DARK VIOLET", CoolColor.DARK_VIOLET))
        finalList.add(listSeventh)

        val listEighth = mutableListOf<Pair<String, Color>>()
        listEighth.add(Pair("PERU", CoolColor.PERU))
        listEighth.add(Pair("CHOCOLATE", CoolColor.CHOCOLATE))
        listEighth.add(Pair("SADDLE BROWN", CoolColor.SADDLE_BROWN))
        listEighth.add(Pair("DARK ORCHID", CoolColor.DARK_ORCHID))
        listEighth.add(Pair("DARK MAGENTA", CoolColor.DARK_MAGENTA))
        listEighth.add(Pair("PURPLE", CoolColor.PURPLE))
        finalList.add(listEighth)

        val listNineth = mutableListOf<Pair<String, Color>>()
        listNineth.add(Pair("SIENNA", CoolColor.SIENNA))
        listNineth.add(Pair("BROWN", CoolColor.BROWN))
        listNineth.add(Pair("MAROON", CoolColor.MAROON))
        listNineth.add(Pair("INDIGO", CoolColor.INDIGO))
        listNineth.add(Pair("SLATE BLUE", CoolColor.SLATE_BLUE))
        listNineth.add(Pair("DARK SLATE BLUE", CoolColor.DARK_SLATE_BLUE))
        finalList.add(listNineth)

        val listTenth = mutableListOf<Pair<String, Color>>()
        listTenth.add(Pair("INDIAN RED", CoolColor.INDIAN_RED))
        listTenth.add(Pair("LIGHT CORAL", CoolColor.LIGHT_CORAL))
        listTenth.add(Pair("SALMON", CoolColor.SALMON))
        listTenth.add(Pair("MEDIUM SLATE BLUE", CoolColor.MEDIUM_SLATE_BLUE))
        listTenth.add(Pair("AQUAL", CoolColor.AQUA))
        listTenth.add(Pair("CYAN", CoolColor.CYAN))
        finalList.add(listTenth)

        val listEleventh = mutableListOf<Pair<String, Color>>()
        listEleventh.add(Pair("DARK SALMON", CoolColor.DARK_SALMON))
        listEleventh.add(Pair("LIGHT SALMON", CoolColor.LIGHT_SALMON))
        listEleventh.add(Pair("CRIMSON", CoolColor.CRIMSON))
        listEleventh.add(Pair("LIGHT CYAN", CoolColor.LIGHT_CYAN))
        listEleventh.add(Pair("PALE TURQUOISE", CoolColor.PALE_TURQUOISE))
        listEleventh.add(Pair("AQUAMARINE", CoolColor.AQUAMARINE))
        finalList.add(listEleventh)

        val listTwelve = mutableListOf<Pair<String, Color>>()
        listTwelve.add(Pair("RED", CoolColor.RED))
        listTwelve.add(Pair("FIREBRICK", CoolColor.FIREBRICK))
        listTwelve.add(Pair("DARK RED", CoolColor.DARK_RED))
        listTwelve.add(Pair("TURQUOISE", CoolColor.TURQUOISE))
        listTwelve.add(Pair("MEDIUM TURQUOISE", CoolColor.MEDIUM_TURQUOISE))
        listTwelve.add(Pair("DARK TURQUOISE", CoolColor.DARK_TURQUOISE))
        finalList.add(listTwelve)

        val listThirteen = mutableListOf<Pair<String, Color>>()
        listThirteen.add(Pair("PINK", CoolColor.PINK))
        listThirteen.add(Pair("LIGHT PINK", CoolColor.LIGHT_PINK))
        listThirteen.add(Pair("HOT PINK", CoolColor.HOT_PINK))
        listThirteen.add(Pair("CADET BLUE", CoolColor.CADET_BLUE))
        listThirteen.add(Pair("STEEL BLUE", CoolColor.STEEL_BLUE))
        listThirteen.add(Pair("LIGHT STEEL", CoolColor.LIGHT_STEEL))
        finalList.add(listThirteen)

        val listFourteen = mutableListOf<Pair<String, Color>>()
        listFourteen.add(Pair("DEEP PINK", CoolColor.DEEP_PINK))
        listFourteen.add(Pair("MEDIUM VIOLET RED", CoolColor.MEDIUM_VIOLET_RED))
        listFourteen.add(Pair("PALE VIOLET RED", CoolColor.PALE_VIOLET_RED))
        listFourteen.add(Pair("POWDER BLUE", CoolColor.POWDER_BLUE))
        listFourteen.add(Pair("LIGHT BLUE", CoolColor.LIGHT_BLUE))
        listFourteen.add(Pair("SKY BLUE", CoolColor.SKY_BLUE))
        finalList.add(listFourteen)

        val listFifteen = mutableListOf<Pair<String, Color>>()
        listFifteen.add(Pair("CORAL", CoolColor.CORAL))
        listFifteen.add(Pair("TOMATO", CoolColor.TOMATO))
        listFifteen.add(Pair("ORANGE RED", CoolColor.ORANGE_RED))
        listFifteen.add(Pair("LIGHT SKY", CoolColor.LIGHT_SKY))
        listFifteen.add(Pair("DEEP SKY BLUE", CoolColor.DEEP_SKY_BLUE))
        listFifteen.add(Pair("DODGER BLUE", CoolColor.DODGER_BLUE))
        finalList.add(listFifteen)

        val listSixteen = mutableListOf<Pair<String, Color>>()
        listSixteen.add(Pair("DARK ORANGE", CoolColor.DARK_ORANGE))
        listSixteen.add(Pair("ORANGE", CoolColor.ORANGE))
        listSixteen.add(Pair("GOLD", CoolColor.GOLD))
        listSixteen.add(Pair("CORNFLOWER BLUE", CoolColor.CORNFLOWER_BLUE))
        listSixteen.add(Pair("ROYAL BLUE", CoolColor.ROYAL_BLUE))
        listSixteen.add(Pair("BLUE", CoolColor.BLUE))
        finalList.add(listSixteen)

        val listSeventeen = mutableListOf<Pair<String, Color>>()
        listSeventeen.add(Pair("YELLOW", CoolColor.YELLOW))
        listSeventeen.add(Pair("LIGHT YELLOW", CoolColor.LIGHT_YELLOW))
        listSeventeen.add(Pair("LEMON CHIFFON", CoolColor.LEMON_CHIFFON))
        listSeventeen.add(Pair("MEDIUM BLUE", CoolColor.MEDIUM_BLUE))
        listSeventeen.add(Pair("DARK BLUE", CoolColor.DARK_BLUE))
        listSeventeen.add(Pair("NAVY", CoolColor.NAVY))
        finalList.add(listSeventeen)

        val listEighteen = mutableListOf<Pair<String, Color>>()
        listEighteen.add(Pair("LIGHT GOLDEN ROD YELLOW", CoolColor.LIGHT_GOLDEN_ROD_YELLOW))
        listEighteen.add(Pair("PAPAYA WHIP", CoolColor.PAPAYA_WHIP))
        listEighteen.add(Pair("MOCCASIN", CoolColor.MOCCASIN))
        listEighteen.add(Pair("MIDNIGHT BLUE", CoolColor.MIDNIGHT_BLUE))
        listEighteen.add(Pair("SNOW", CoolColor.SNOW))
        listEighteen.add(Pair("HONEY DEW", CoolColor.HONEY_DEW))
        finalList.add(listEighteen)

        val listNineteen = mutableListOf<Pair<String, Color>>()
        listNineteen.add(Pair("PEACH PUFF", CoolColor.PEACH_PUFF))
        listNineteen.add(Pair("PALE GOLDEN ROD", CoolColor.PALE_GOLDEN_ROD))
        listNineteen.add(Pair("KHAKI", CoolColor.KHAKI))
        listNineteen.add(Pair("MINT CREAM", CoolColor.MINT_CREAM))
        listNineteen.add(Pair("AZURE", CoolColor.AZURE))
        listNineteen.add(Pair("ALICE BLUE", CoolColor.ALICE_BLUE))
        finalList.add(listNineteen)

        val listTwenty = mutableListOf<Pair<String, Color>>()
        listTwenty.add(Pair("DARK KHAKI", CoolColor.DARK_KHAKI))
        listTwenty.add(Pair("GREEN YELLOW", CoolColor.GREEN_YELLOW))
        listTwenty.add(Pair("CHARTREUSE", CoolColor.CHARTREUSE))
        listTwenty.add(Pair("GHOST WHITE", CoolColor.GHOST_WHITE))
        listTwenty.add(Pair("WHITE SMOKE", CoolColor.WHITE_SMOKE))
        listTwenty.add(Pair("SEASHELL", CoolColor.SEASHELL))
        finalList.add(listTwenty)

        val listTwentyOne = mutableListOf<Pair<String, Color>>()
        listTwentyOne.add(Pair("BEIGE", CoolColor.BEIGE))
        listTwentyOne.add(Pair("OLDLACE", CoolColor.OLDLACE))
        listTwentyOne.add(Pair("FLORAL WHITE", CoolColor.FLORAL_WHITE))
        listTwentyOne.add(Pair("IVORY", CoolColor.IVORY))
        listTwentyOne.add(Pair("ANTIQUE WHITE", CoolColor.ANTIQUE_WHITE))
        listTwentyOne.add(Pair("LINEN", CoolColor.LINEN))
        listTwentyOne.add(Pair("LAVENDER BRISH", CoolColor.LAVENDER_BRUSH))
        listTwentyOne.add(Pair("MISTY ROSE", CoolColor.MISTY_ROSE))
        finalList.add(listTwentyOne)

        return finalList
    }
}

object CoolColor {
    val GAINSBORO = Color(0xffDCDCDC)
    val LIGHT_GREY = Color(0xffD3D3D3)
    val SILVER = Color(0xffC0C0C0)
    val DARK_GREY = Color(0xffA9A9A9)
    val GREY = Color(0xff808080)
    val DIM_GREY = Color(0xff696969)
    val LIGHT_SLATE_GREY = Color(0xff778899)
    val SLATE_GREY = Color(0xff708090)
    val DARK_SLATE_GREY = Color(0xff2F4F4F)
    val BLACK = Color(0xff000000)
    val CORN_SILK = Color(0xffFFF8DC)
    val BLANCHED_ALMOND = Color(0xffFFEBCD)
    val BISQUE = Color(0xffFFE4C4)
    val NAVAJO_WHITE = Color(0xffFFDEAD)
    val WHEAT = Color(0xffF5DEB3)
    val BURLYWOOD = Color(0xffF5DEB3)
    val TAN = Color(0xffD2B48C)
    val ROSY_BROWN = Color(0xffBC8F8F)
    val SANDY_BROWN = Color(0xffF4A460)
    val GOLDEN_ROD = Color(0xffDAA520)
    val DARK_GOLDEN_ROD = Color(0xffB8860B)
    val PERU = Color(0xffCD853F)
    val CHOCOLATE = Color(0xffD2691E)
    val SADDLE_BROWN = Color(0xff8B4513)
    val SIENNA = Color(0xffA0522D)
    val BROWN = Color(0xffA52A2A)
    val MAROON = Color(0xff800000)
    val INDIAN_RED = Color(0xffCD5C5C)
    val LIGHT_CORAL = Color(0xffF08080)
    val SALMON = Color(0xffFA8072)
    val DARK_SALMON = Color(0xffE9967A)
    val LIGHT_SALMON = Color(0xffFFA07A)
    val CRIMSON = Color(0xffDC143C)
    val RED = Color(0xffFF0000)
    val FIREBRICK = Color(0xffB22222)
    val DARK_RED = Color(0xff8B0000)
    val PINK = Color(0xffFFC0CB)
    val LIGHT_PINK = Color(0xffFFB6C1)
    val HOT_PINK = Color(0xffFF69B4)
    val DEEP_PINK = Color(0xffFF1493)
    val MEDIUM_VIOLET_RED = Color(0xffC71585)
    val PALE_VIOLET_RED = Color(0xffDB7093)
    val CORAL = Color(0xffFF7F50)
    val TOMATO = Color(0xffFF6347)
    val ORANGE_RED = Color(0xffFF4500)
    val DARK_ORANGE = Color(0xffFF8C00)
    val ORANGE = Color(0xffFFA500)
    val GOLD = Color(0xffFFD700)
    val YELLOW = Color(0xffFFFF00)
    val LIGHT_YELLOW = Color(0xffFFFFE0)
    val LEMON_CHIFFON = Color(0xffFFFACD)
    val LIGHT_GOLDEN_ROD_YELLOW = Color(0xffFAFAD2)
    val PAPAYA_WHIP = Color(0xffFFEFD5)
    val MOCCASIN = Color(0xffFFE4B5)
    val PEACH_PUFF = Color(0xffFFDAB9)
    val PALE_GOLDEN_ROD = Color(0xffEEE8AA)
    val KHAKI = Color(0xffF0E68C)
    val DARK_KHAKI = Color(0xffBDB76B)
    val GREEN_YELLOW = Color(0xffADFF2F)
    val CHARTREUSE = Color(0xff7FFF00)
    val LAWN_GREEN = Color(0xff7CFC00)
    val LIME = Color(0xff00FF00)
    val LIME_GREEN = Color(0xff32CD32)
    val DARK_OLIVE = Color(0xff556B2F)
    val MEDIUM_AQUAMARINE = Color(0xff66CDAA)
    val DARK_SEAGREEN = Color(0xff8FBC8B)
    val LIGHT_SEAGREEN = Color(0xff20B2AA)
    val DARK_CYAN = Color(0xff008B8B)
    val TEAL = Color(0xff008080)
    val LAVENDER = Color(0xffE6E6FA)
    val THISTLE = Color(0xffD8BFD8)
    val PLUM = Color(0xffDDA0DD)
    val VIOLET = Color(0xffEE82EE)
    val ORCHID = Color(0xffDA70D6)
    val FUCHSIA = Color(0xffFF00FF)
    val MAGENTA = Color(0xffFF00FF)
    val MEDIUM_ORCHID = Color(0xffBA55D3)
    val MEDIUM_PURPLE = Color(0xff9370DB)
    val REBECCA_PURPLE = Color(0xff663399)
    val BLUE_VIOLET = Color(0xff8A2BE2)
    val DARK_VIOLET = Color(0xff9400D3)
    val DARK_ORCHID = Color(0xff9932CC)
    val DARK_MAGENTA = Color(0xff8B008B)
    val PURPLE = Color(0xff800080)
    val INDIGO = Color(0xff4B0082)
    val SLATE_BLUE = Color(0xff6A5ACD)
    val DARK_SLATE_BLUE = Color(0xff483D8B)
    val MEDIUM_SLATE_BLUE = Color(0xff7B68EE)
    val AQUA = Color(0xff00FFFF)
    val CYAN = Color(0xff00FFFF)
    val LIGHT_CYAN = Color(0xffE0FFFF)
    val PALE_TURQUOISE = Color(0xffAFEEEE)
    val AQUAMARINE = Color(0xff7FFFD4)
    val TURQUOISE = Color(0xff40E0D0)
    val MEDIUM_TURQUOISE = Color(0xff48D1CC)
    val DARK_TURQUOISE = Color(0xff00CED1)
    val CADET_BLUE = Color(0xff5F9EA0)
    val STEEL_BLUE = Color(0xff4682B4)
    val LIGHT_STEEL = Color(0xffB0C4DE)
    val POWDER_BLUE = Color(0xffB0E0E6)
    val LIGHT_BLUE = Color(0xffADD8E6)
    val SKY_BLUE = Color(0xff87CEEB)
    val LIGHT_SKY = Color(0xff87CEFA)
    val DEEP_SKY_BLUE = Color(0xff00BFFF)
    val DODGER_BLUE = Color(0xff1E90FF)
    val CORNFLOWER_BLUE = Color(0xff6495ED)
    val ROYAL_BLUE = Color(0xff4169E1)
    val BLUE = Color(0xff0000FF)
    val MEDIUM_BLUE = Color(0xff0000CD)
    val DARK_BLUE = Color(0xff00008B)
    val NAVY = Color(0xff000080)
    val MIDNIGHT_BLUE = Color(0xff191970)
    val WHITE = Color(0xffFFFFFF)
    val SNOW = Color(0xffFFFAFA)
    val HONEY_DEW = Color(0xffF0FFF0)
    val MINT_CREAM = Color(0xffF5FFFA)
    val AZURE = Color(0xffF0FFFF)
    val ALICE_BLUE = Color(0xffF0F8FF)
    val GHOST_WHITE = Color(0xffF8F8FF)
    val WHITE_SMOKE = Color(0xffF5F5F5)
    val SEASHELL = Color(0xffFFF5EE)
    val BEIGE = Color(0xffF5F5DC)
    val OLDLACE = Color(0xffFDF5E6)
    val FLORAL_WHITE = Color(0xffFFFAF0)
    val IVORY = Color(0xffFFFFF0)
    val ANTIQUE_WHITE = Color(0xffFAEBD7)
    val LINEN = Color(0xffFAF0E6)
    val LAVENDER_BRUSH = Color(0xffFFF0F5)
    val MISTY_ROSE = Color(0xffFFE4E1)

}